provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  csharp-secret:
    lang: csharp
    handler: ./csharp-secret
    image: alexellis2/csharp-secret:0.1
    secrets:
      - api-key
